### ISSUE TITLE
Add custom fields to every log

### ISSUE THREAD

**Issue by brandonwestcott** [logzio/logzio-lambda-extensions#11]
After a lot of searching the internet, I was ecstatic to see logz.io working on log aggregation via the lambda extensions. I believe this approach is much cleaner and a more scalable solution over the traditional cloud watch stream approach.

One question, is it possible to add custom field / value pairs that would exist outside of each log line, ex setting `app_name: cool app` explicitly? The benefit being one could deploy the layer and organize the logs without having to change the log lines across all their lambda functions.

To note, I tried setting an explicit `app_name` field/value in `GROK_PATTERNS: "{\"app_name\":\"cool app\",\"my_message\":\".*\"}"`, and omitting it from `LOGS_FORMAT`, ex `LOGS_FORMAT="%{app_message:my_message}"`, but that didn't send through `app_name`.

One feature proposal to solve this could be to add a new env var, ex `LOGZIO_STATIC_FIELDS="{\"app_name\":\"cool app\"}"`, which would merge in that json into the parsed log

**Comment by mirii1994** [comment]
Hi @brandonwestcott thank you for the feedback, happy to hear that you like it!

We will add your request to our backlog, but currently we don't have an ETA for this.
If you want to, you are more than welcome to contribute to this project!

In the meantime, you can add custom fields from your code, by using a logger module.
Not sure which language you're using in your Lambda, but for example in python you can add to your logs some fields by using `extra` when logging (see [python documentation](https://docs.python.org/3/library/logging.html#logging.Logger.debug)).
The grok pattern is not for adding custom fields, it's only to parse fields. After using a logger that formats logs, you can use the grok feature to parse those fields correctly.
