### ISSUE TITLE
Log-Escape-Ception if ENABLE_EXTENSION_LOGS=true

### ISSUE THREAD

**Issue by m-kn** [logzio/logzio-lambda-extensions#18]
Hi again,

while trying to debug some `GROK_PATTERNS` & `LOGS_FORMAT` combos, I set `ENABLE_EXTENSION_LOGS=true` and got something that looks like recursively escaped and therefore incredibly long log lines, split into multiple events/log lines in Logz.io and CloudWatch.

For example

line 1
`time="2022-03-11T13:15:37Z" level=info msg="ignore if this log is not JSON. while checking if log \\\\\\\\\\\\\\`

line 2

`\\\\\... (editor says it's 1600 backslashes) ... \\\\\\"Extension id: 7941873f-3b86-4ae3-aa94-f3fabb3bbcbd\\\ ... ( 1900 backslashes) ... \\\\n\\\\\ ...  (3000+ backslashes) ... \\\"time\\\\\ (3000+ of backslashes)  \\\\\"2022-03-11T13:15:27.552Z\\\\\\  (thousands of backslashes) \\\\"type\\\\\ (thousands of backslashes)  \\\\\\\\"extension\\\\ ... (more backslashes) ... \\\\\"record\\\ ... (thousands of backslashes) ... \\\\"time=\\\\ (thousands of backslashes) \\\\"2022-03-11T13:15:27Z\\\ ... (couple more backslashes) ... \\\\" agent=logzioLogsExtension`
	
line 3
`
\\\\ ... (a thousand slashes) ... \\\"Extension id: 7941873f-3b86-4ae3-aa94-f3fabb3bbcbd\\\\ (two thousand) \\\\n\\\\\ (4000+) \"time\\\\ (4000+) \\\\"2022-03-11T13:15:27.552Z\\\\ (4000+) \\\"type\\\ (slashes) \\\"extension\\\ (slahes) \\\\"record\\\ (slashes) \\\"time=\\\ (slashes) \\\\"2022-03-11T13:15:27Z\\\\\\ (couple more slashes) \\\\\\ is JSON, receive this : invalid character '\\\\' looking for beginning of value" agent=logzioLogsExtension`

I tried to only add comments inside of the various mountains of slashes, so the order outside should still be correct. Looks like a bunch very very very escaped `"` and some `\n`

These logs show up in both CloudWatch and Logz.io if `ENABLE_EXTENSION_LOGS=true`, but CloudWatch allows some more characters per line, so they're split at different points. 

Fortunately the extension logs to CloudWatch even if `ENABLE_EXTENSION_LOGS=false`, so I managed to work around this issue. The doc says that flag only switches the export to Logz.io on/off, but the flags name sounds like it enables/disables extensions log in both.

**Comment by mirii1994** [comment]
Hi @m-kn , thanks for reaching out. We'll work on a fix for this issue.
