### ISSUE TITLE
Can not add formatted logs

### ISSUE THREAD

**Issue by Allc9001** [logzio/logzio-lambda-extensions#23]
Hi, 

I've got formatted logs that I want to break out using `GROK_PATTERNS` and `LOGS_FORMAT`. While this works for a simple example I can not get it to work when I want to break out 2 fields. I'm not sure if I'm using it wrong or if this is a bug ? Hopefully you can tell me.

Here is the log line that I'm trying to consume:

```
08:26:56.533 [main] DEBUG com.amazon.test.Stuff - debug message
```

Here is my `GROK_PATTERNS`:
```
{"mytime":"%{NOTSPACE}","remain":".*"}
```
And my `LOGS_FORMAT`:
```
%{mytime:timemine} : %{myreamin:remain}
```

The above config causes neither field (`timemine` and `remain`) to appear in logz. I'm not sure that having a space in the `LOGS_FORMAT` (either side of the `:`) is correct ?
 
thanks

Simon

**Comment by 8naama** [comment]
Hey @Allc9001! Apologies for the long await for a reply!


In case this is still relevant;
- `GROK_PATTERNS` defines the grok patterns that we want to use and the regex behind them, so it's not possible to use `%{NOTSPACE}` as the regex, Instead, you'll need to use:
``` json
{"mytime":"\\S+","remain":".*"}
```

- `LOGS_FORMAT` is the actual full grok pattern that matches the needed log format, and it uses the grok patterns that were defined in `GROK_PATTERNS`.
- The syntax is:
``` grok
%{GROK_PATTERN_NAME:WANTED_FIELD_NAME}
```
So in your case you should use:
``` grok
%{mytime:timemine} %{reamin:myreamin}
```
Which will parse out the fields `timemine` and `myreamin`.

-----------
We'll improve the docs regarding the usage of `GROK_PATTERNS` and `LOGS_FORMAT`.
Thank you for your question!
