### ISSUE TITLE
To add arm64 support

### ISSUE THREAD

**Issue by zhaow-de** [logzio/logzio-lambda-extensions#29]
With the rising push of Graviton processor adoption by AWS, using the ARM64 environment for lambda functions makes more sense. It would be nice if this extension could be cross-compiled for arm64 architecture and pushed as a separate layer side-by-side with the X86_64 one.

**Comment by 8naama** [comment]
Hey @zhaow-de, thank you! We've added lambda layer for ARM64 support that you can find [here](https://github.com/logzio/logzio-lambda-extensions/tree/main/logzio-lambda-extensions-logs#arm64-architecture).
