### ISSUE TITLE
Add support for the ca-central-1 AWS region

### ISSUE THREAD

**Issue by mduzee** [logzio/logzio-lambda-extensions#7]
We have multiple deployments in the ca-central-1 region of AWS and would like to use the lambda extension there.

**Comment by mirii1994** [comment]
Hi @mduzee @calebpalmer thanks for reaching out!
You can now use the extension (v0.1.0) in ca-central-1 :)

**Comment by mduzee** [comment]
Following the instructions here:
 https://docs.logz.io/shipping/log-sources/lambda-extensions.html#console

I specified the following ARN for the layer: 
arn:aws:lambda:ca-central-1:486140753397:layer:LogzioLambdaExtensionLogs:2

Unfortunately I get the following error:
You are not authorized to perform: lambda:GetLayerVersion.

**Comment by mirii1994** [comment]
Hi @mduzee ,
Can you please try to perform that step again? We've changed the permissions and it should work now :)

**Comment by mduzee** [comment]
Works great, thanks!
