### ISSUE TITLE
Add additional fields to logs

### ISSUE THREAD

**Issue by mduzee** [logzio/logzio-lambda-extensions#9]
By default the logs that come out of Lambda have the following format:
"[%(levelname)s]\t%(asctime)s.%(msecs)03dZ\t%(aws_request_id)s\t%(message)s\n"

Do you have any suggestions on how to parse the extra information into their own fields? Ideally I would have 5 different fields in Logzio, which would make it much easier to search through the logs.

**Comment by mirii1994** [comment]
Hi @mduzee ,
Currently the extension gets the logs as a string, and passes them that way, so it does not parse the information into their own fields.
We are working on a new extension version, that will allow the parsing :)

**Comment by mirii1994** [comment]
@mduzee v0.2.0 is out, and supports parsing formatted logs using grok patterns.
See [this section](https://github.com/logzio/logzio-lambda-extensions/tree/main/logzio-lambda-extensions-logs#parsing-logs) for more info on how to use it.
Please let us know if this solves your issue :)

**Comment by mduzee** [comment]
Thats great, thanks a lot!

**Comment by mirii1994** [comment]
Closing this issue.
Feel free to re-open, or create a new one if something comes up.
